FROM alpine:latest

WORKDIR /app

COPY brokerApp /app/brokerApp

ARG MOVIEDB_SERVICE_URL
ENV MOVIEDB_SERVICE_URL=${MOVIEDB_SERVICE_URL}

ARG REDIS_PROD_PASS
ENV REDIS_PROD_PASS=${REDIS_PROD_PASS}

ARG PAYMENT_SERVICE_URL
ENV PAYMENT_SERVICE_URL=${PAYMENT_SERVICE_URL}

ARG AUTH_SERVICE_URL
ENV AUTH_SERVICE_URL=${AUTH_SERVICE_URL}

ARG RABBITMQ_PRODUCER_SERVICE
ENV RABBITMQ_PRODUCER_SERVICE=${RABBITMQ_PRODUCER_SERVICE}

RUN chmod +x brokerApp

CMD ["./brokerApp"]